CasaSoftUmbracoUSkinnedTemplate/Controllers/Shared/SubmitPhoto/_SubmitPhotoFormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CS.Common.Umbraco.Services.Umbraco.Wrappers.Services;
using CSTemplate.Code.Constants;
using CSTemplate.Code.Models.Shared;
using CSTemplate.Code.Services.SubmitPhoto;
using Umbraco.Web.Models;

namespace CasaSoftUmbracoUSkinnedTemplate.Controllers.Shared.SubmitPhoto
{
    [OutputCache(CacheProfile = ConstantValues.Cache_Profile_Name_By_Url_And_Specific_User)]
    public partial class _SubmitPhotoFormController : USNBaseController
    {
        private readonly IUmbracoControllerWrapperService _umbracoControllerWrapperService;
        private readonly IGetSubmitPhotosFormService _getSubmitPhotoSelectionService;

        public _SubmitPhotoFormController(
            IUmbracoControllerWrapperService umbracoControllerWrapperService,
            IGetSubmitPhotosFormService getSubmitPhotoSelectionService
        )
        {
            _umbracoControllerWrapperService = umbracoControllerWrapperService;
            _getSubmitPhotoSelectionService = getSubmitPhotoSelectionService;
        }

        // GET: _SubmitPhotoForm
        //public virtual ActionResult _SubmitPhotoForm(RenderModel model)
        //{
        //    var umbracoHelper = _umbracoControllerWrapperService.GetUmbracoHelperForUmbracoController(this);

        //    _SubmitPhotoFormModel submitPhotoFormModel = _getSubmitPhotoSelectionService.Get(umbracoHelper, model.Content);
        //    return base.Populate(submitPhotoFormModel);
        //}
    }
}

CasaSoftUmbracoUSkinnedTemplate/Controllers/Shared/SubmitStorytellingForm/_SubmitStoryTellingFormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CS.Common.Umbraco.Services.Umbraco.Wrappers.Services;
using CSTemplate.Code.Constants;
using CSTemplate.Code.Models.Shared;
using CSTemplate.Code.Services.ProfilePage;
using CSTemplate.Code.Services.SubmitStorytelling;
using Umbraco.Web.Models;

namespace CasaSoftUmbracoUSkinnedTemplate.Controllers.Shared.SubmitStorytellingForm
{
    [OutputCache(CacheProfile = ConstantValues.Cache_Profile_Name_By_Url_And_Specific_User)]
    public partial class _SubmitStoryTellingFormController : USNBaseController
    {

        private readonly IUmbracoControllerWrapperService _umbracoControllerWrapperService;
        private readonly IGetSubmitStoryTellingFormService _getSubmitStoryTellingFormService;

        public _SubmitStoryTellingFormController(
            IUmbracoControllerWrapperService umbracoControllerWrapperService,
            IGetSubmitStoryTellingFormService getSubmitStoryTellingFormService
        )
        {
            _umbracoControllerWrapperService = umbracoControllerWrapperService;
            _getSubmitStoryTellingFormService = getSubmitStoryTellingFormService;
        }

        // GET: SubmitStoryTellingForm
        //public virtual ActionResult _SubmitStoryTellingForm(RenderModel model)
        //{
        //    var umbracoHelper = _umbracoControllerWrapperService.GetUmbracoHelperForUmbracoController(this);
        //    _SubmitStoryTellingFormModel submitStoryTellingFormModel =
        //        _getSubmitStoryTellingFormService.Get(umbracoHelper, model.Content);
        //    return base.Populate(submitStoryTellingFormModel);
        //}
    }
}

CasaSoftUmbracoUSkinnedTemplate/Controllers/Shared/SurfaceControllers/DeleteRecordFromOrderHistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CS.Common.Umbraco.Services.Umbraco.Wrappers.Services;
using CSTemplate.Code.Constants;
using CSTemplate.Code.Models.Shared.OrderHistoryItem;
using CSTemplate.Code.Services.Orders;
using Umbraco.Web.Mvc;

namespace CasaSoftUmbracoUSkinnedTemplate.Controllers.Shared.SurfaceControllers
{
    public partial class DeleteRecordFromOrderHistoryController : SurfaceController
    {
        private readonly IDeleteOrderFilterByOrderIdService _deleteOrderFilterByOrderIdService;
        private readonly IUmbracoControllerWrapperService _umbracoControllerWrapperService;

        public DeleteRecordFromOrderHistoryController(IDeleteOrderFilterByOrderIdService deleteOrderFilterByOrderIdService, IUmbracoControllerWrapperService umbracoControllerWrapperService)
        {
            _umbracoControllerWrapperService = umbracoControllerWrapperService;
            _deleteOrderFilterByOrderIdService = deleteOrderFilterByOrderIdService;
        }
        // GET: SubmitPhotoFormSurface
        [HttpPost]
        public virtual ActionResult HandleDeleteRecordFromOrderHistory(_OrderHistoryItem OrderHistoryItemForForm)
        {
            //Radek notes:
            //I created new PaymentStatus - "DELETED". Check Enums.paymentstatus

            //inside this action you have to change the payment status of the order for "deleted".
            //then we will redirect the user to the same OrderSummaryPage but
            // in the OrderHistoryPageDataController return only list of orders that have status different that "deleted". So if the transaction has a status "deleted" don't show it".

            //also make sure that "request feedback" button on the submission full page won't redirect to deleted transaction but it will create a new order if the old one has been deleted by user. 
            var umbracoHelper = _umbracoControllerWrapperService.GetUmbracoHelperForUmbracoController(this);
            int orderId = int.Parse(OrderHistoryItemForForm.OrderNumber);
            if (orderId > 0)
            {
                _deleteOrderFilterByOrderIdService.Delete(umbracoHelper, orderId);
            }

            HttpRuntime.Cache.Remove(ConstantValues.Cache_Key_Submission_Full_Page);


            return RedirectToCurrentUmbracoPage();
        }
    }
}

CasaSoftUmbracoUSkinnedTemplate/Controllers/Shared/SurfaceControllers/MasterSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CS.Common.Umbraco.Services.Umbraco.Wrappers.Services;
using CSTemplate.Code.Constants;
using CSTemplate.Code.Models.Shared;
using Umbraco.Web.Mvc;

namespace CasaSoftUmbracoUSkinnedTemplate.Controllers.Shared.SurfaceControllers
{
    public partial class MasterSurfaceController : SurfaceController
    {
        private readonly IUmbracoHelperService _umbracoHelperService;
        private readonly IUmbracoControllerWrapperService _umbracoControllerWrapperService;

        public MasterSurfaceController(IUmbracoHelperService umbracoHelperService, IUmbracoControllerWrapperService umrbaControllerWrapperService)
        {
            _umbracoControllerWrapperService = umrbaControllerWrapperService;
            _umbracoHelperService = umbracoHelperService;
        }

        /// <summary>
        /// Creates an antiforgery token without being cached
        /// </summary>
        /// <returns>AntiForgery Token</returns>
        [ChildActionOnly]
        public virtual ContentResult GetAntiForgeryToken()
        {
            using (var viewPage = new ViewPage())
            {
                var htmlHelper = new HtmlHelper(new ViewContext(), viewPage);
                var token = htmlHelper.AntiForgeryToken();
                return Content(token.ToHtmlString());
            }
        }

        [ChildActionOnly]
        public virtual ActionResult GetFooterPayments()
        {
            var umbracoHelper = _umbracoControllerWrapperService.GetUmbracoHelperForUmbracoController(this);

            var footerPaymentsModel = new _FooterPaymentMethodModel();


            footerPaymentsModel.FooterPhotoTitleImgURL = "/dist/assets/img/logo.png";
            footerPaymentsModel.FooterText = _umbracoHelperService.GetDictionaryValueOrUpdateDefaultValueIfEmpty(umbracoHelper, Enums.DictionaryKey.Footer_Description_Company) ;
            footerPaymentsModel.FooterPaymentMethodText = _umbracoHelperService.GetDictionaryValueOrUpdateDefaultValueIfEmpty(umbracoHelper, Enums.DictionaryKey.Footer_Payments_Method_Description);
            footerPaymentsModel.FooterPaymentMethodImgURL1 = "/dist/assets/img/securepayment.png";
            footerPaymentsModel.FooterPaymentMethodImgURL2 = "/dist/assets/img/visa.png";
            footerPaymentsModel.FooterPaymentMethodImgURL3 = "/dist/assets/img/mastercard.png";


            return PartialView(MVC.Shared.Views.FooterPaymentMethod._FooterPaymentMethod, footerPaymentsModel);
        }

    }
}

CasaSoftUmbracoUSkinnedTemplate/Controllers/Shared/SurfaceControllers/SubmitPhotoFormSurfaceController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CS.Common.Umbraco.Services.Umbraco.Wrappers.Services;
using CSTemplate.Code.Constants;
using CSTemplate.Code.Models.Shared;
using CSTemplate.Code.Services.Photos;
using Umbraco.Web.Mvc;

namespace CasaSoftUmbracoUSkinnedTemplate.Controllers.Shared.SurfaceControllers
{
    public partial class SubmitPhotoFormSurfaceController : SurfaceController
    {
        private readonly IUmbracoControllerWrapperService _umbracoControllerWrapperService;
        private readonly ISubmitNewPhotosService _submitNewPhotosService;

        public SubmitPhotoFormSurfaceController(IUmbracoControllerWrapperService controllerWrapperService,ISubmitNewPhotosService submitNewPhotosService)
        {
            
            _submitNewPhotosService = submitNewPhotosService;
            _umbracoControllerWrapperService = controllerWrapperService;
        }

        // GET: SubmitPhotoFormSurface
        [HttpPost]
        public virtual ActionResult SubmitPhotoForm(_SubmitPhotoFormModel submitPhotoFormModel)
        {
            var umbracoHelper = _umbracoControllerWrapperService.GetUmbracoHelperForUmbracoController(this);
            var userId = Members.GetCurrentMemberId();
            var submitModel = submitPhotoFormModel.ListOfSubmitPhotos;
            var result = _submitNewPhotosService.Submit(umbracoHelper, userId, submitModel);
            var redirectToUrl = result==true?CSTemplate.Code.Constants.ConstantValues.Order_Summary_Page_Link: CSTemplate.Code.Constants.ConstantValues.Submit_Photo_Page_Link;


            return base.Redirect(redirectToUrl);
        }
    }
}

CasaSoftUmbracoUSkinnedTemplate/Controllers/Shared/SurfaceControllers/SubmitStoryTellingFormSurfaceController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CS.Common.Constants;
using CS.Common.Umbraco.Services.Umbraco.Wrappers.Services;
using CSTemplate.Code.Constants;
using CSTemplate.Code.Models.Shared;
using CSTemplate.Code.Services.AwardCategory;
using CSTemplate.Code.Services.Photos;
using Umbraco.Web.Mvc;

namespace CasaSoftUmbracoUSkinnedTemplate.Controllers.Shared.SurfaceControllers
{
    public partial class SubmitStoryTellingFormSurfaceController : SurfaceController
    {
        private readonly ISubmitNewPhotosService _submitNewPhotosService;
        private readonly IUmbracoControllerWrapperService _umbracoControllerWrapperService;
        private readonly IGetAwardCategoryStoryTellingService _getAwardCategoryStoryTellingService;

        // GET: SubmitStoryTellingFormSurface
        public SubmitStoryTellingFormSurfaceController(
            ISubmitNewPhotosService submitNewPhotosService,
            IUmbracoControllerWrapperService umbracoControllerWrapperService,
            IGetAwardCategoryStoryTellingService getAwardCategoryStoryTellingService
            )
        {
            _getAwardCategoryStoryTellingService = getAwardCategoryStoryTellingService;
            _umbracoControllerWrapperService = umbracoControllerWrapperService;
            _submitNewPhotosService = submitNewPhotosService;
        }

        [System.Web.Http.HttpPost]
        public virtual ActionResult SubmitStoryTellingForm(_SubmitStoryTellingFormModel submitStoryTellingFormModel)
        {
           
            var umbracoHelper = _umbracoControllerWrapperService.GetUmbracoHelperForUmbracoController(this);
            var currentMemberId = Members.GetCurrentMemberId();
            var submitModel = submitStoryTellingFormModel.SubmitPhotoItem;
            var category = _getAwardCategoryStoryTellingService.Get(umbracoHelper);
            submitModel.CategorySelected = category.FirstOrDefault().Value;

            var result = _submitNewPhotosService.Submit(umbracoHelper, currentMemberId, new List<_SubmitPhotoItemModel>() { submitModel });

            var redirectToUrl = result == true ? CSTemplate.Code.Constants.ConstantValues.Order_Summary_Page_Link : CSTemplate.Code.Constants.ConstantValues.Submit_StoryTelling_Page_Link;
            return base.Redirect(redirectToUrl);
           

            
        }
    }
}

CasaSoftUmbracoUSkinnedTemplate/Views/Shared/SubmitPhotoForm/_SubmitPhotoForm.cshtml
@inherits UmbracoViewPage<CSTemplate.Code.Models.Shared._SubmitPhotoFormModel>


@using (Html.BeginForm("SubmitPhotoForm", "SubmitPhotoFormSurface", FormMethod.Post, new {enctype = "multipart/form-data", @class= "submit-photos-form" }))
{


        <div class="number-photos-container">
            <p>@Model.ExplanationFormText</p>
            <p class="required">@Model.Required</p>

            <div class="form-group">
                @Html.LabelFor(x => Model.NumberOfPhotosSelected, new { @class = "label-required" })
                @Html.DropDownListFor(model => model.NumberOfPhotosSelected, Model.NumberOfPhotos, new { @class = "form-control selectInput" })
            </div>
        </div>
        <div class="submit-photos-container">
            <div class="submit-photos-form-container">
                @{
                    var cnt = 0;
                    foreach (var photoForm in Model.ListOfSubmitPhotos)
                    {
                        @Html.Partial("SubmitPhotoForm/_SubmitPhotoItem", photoForm, new ViewDataDictionary()
                        {
                            TemplateInfo = new TemplateInfo()
                            {
                                HtmlFieldPrefix = "ListOfSubmitPhotos[" + cnt + "]"
                            }
                        })
                        cnt++;
                    }
                }

            </div>
            <div class="form-group checkbox-container">

                <label class="label-required checkbox-label" for="TermsConditions">
                    @Html.HiddenFor(m => Model.True)
                    @Html.CheckBoxFor(x => Model.TermsConditions, new { @class = "checkbox-input" })
                    <span class="checkmark"></span>

                    <span class="label-text">@Html.Raw(Model.TermsAndConditionsText)</span>

                </label>
                 @Html.ValidationMessageFor(x => Model.TermsConditions, "")
                <br /><br />
                <label class="label-required">
                    <span class="label-text">@Html.Raw(Model.UploadInformationText)</span>
                </label>
               

            </div>
           
            <button type="submit" class="btn" id="submitButtonForm">@Model.ButtonFormText</button>
        </div>
}

CasaSoftUmbracoUSkinnedTemplate/Views/Shared/SubmitPhotoForm/_SubmitPhotoItem.cshtml
@inherits UmbracoViewPage<CSTemplate.Code.Models.Shared._SubmitPhotoItemModel>
<div id="SubmitPhoto_1" class="submit-photo-form">
    <p class="title">@Model.TitleForm <span class="photo-number"></span></p>
    <p class="required">@Model.Required</p>
    
   

    @if (!@Model.isAStortyTelling)
    {
        <div class="form-group photo-title-group">
            @Html.LabelFor(x => Model.PhotoTitle, new { @class = "label-required label-title", @for= "PhotoTitle_1" })
            @Html.TextBoxFor(x => Model.PhotoTitle, new { @class = "form-control photo-title", id = "PhotoTitle_1", required = "required" })
            @Html.ValidationMessageFor(x => Model.PhotoTitle, "", new { @class = "title-validation-field" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => Model.CategorySelected, new { @class = "label-required label-category", @for= "PhotoCategory_1" })
            @Html.DropDownListFor(x => Model.CategorySelected, new SelectList(Model.CategorySelectListItems, "Value", "Text"), new { @class = "form-control photo-category", id = "PhotoCategory_1" })
        </div>
        
       
        <div class="file-field input-field form-group photo-upload-group">

            @Html.LabelFor(x => Model.SubmitPhoto, new { @class = "label-required custom-file-label label-file", @for = "PhotoFile_1" })
            @Html.TextBoxFor(x => Model.SubmitPhoto, new { type = "file", @class = "form-control photo-file custom-file-input", id = "PhotoFile_1", accept = "image/*", required = "required" })
            @Html.ValidationMessageFor(x => Model.SubmitPhoto, "", new { @class = "photo-upload-validation-field" })
          
            

        </div>
    }
    @if (@Model.isAStortyTelling)
    {
        <div class="form-group">
          
            @Html.LabelFor(x => Model.StoryTellingTitle, new { @class = "label-required", @for= "PhotoTitle_1" })
            @Html.TextBoxFor(x => Model.StoryTellingTitle, new { @class = "form-control photo-title", id = "PhotoTitle_1"})
            @Html.ValidationMessageFor(x => Model.StoryTellingTitle, "")
        </div>

        <div class="form-group">
            
            @Html.LabelFor(x => Model.SubmitPhoto, new {@class = "label-required", @for= "PhotoFile_1" })
            @Html.TextBoxFor(x => Model.SubmitPhoto, new {type = "file", @class = "form-control photo-file", id = "PhotoFile_1", multiple = "multiple", accept = "image/*"})
            @Html.ValidationMessageFor(x => Model.SubmitPhoto)

        </div>
    }
    <div class="form-group photo-date-group">
        @Html.LabelFor(x => Model.PhotoDate, new { @class = "label-required label-timepicker", @for= "PhotoDate_1" })
        @Html.TextBoxFor(x => Model.PhotoDate, new { @class = "form-control timepicker", id = "PhotoDate_1", type = "text", required = "required" })
        @Html.ValidationMessageFor(x => Model.PhotoDate, "", new { @class = "photo-date-validation-field" })


    </div>

    @*<div class="form-group">
        @Html.LabelFor(x => Model.Location, new { @class = "label-required" })
        @Html.TextBoxFor(x => Model.Location, new { @class = "form-control photo-location", id = "PhotoLocation_1" })
        @Html.ValidationMessageFor(x => Model.Location, "")


    </div>*@
    @if (!@Model.isAStortyTelling)
    {
        <div class="form-group photo-description-group">
            @Html.LabelFor(x => Model.DescriptionPhoto, new { @class = "label-required label-description", @for= "PhotoDescription_1" })
            @Html.TextAreaFor(x => Model.DescriptionPhoto, new { @class = "form-control photo-description", id = "PhotoDescription_1", rows = 5, maxlength = 150, required = "required" })
            @Html.ValidationMessageFor(x => Model.DescriptionPhoto, "", new { @class = "photo-description-validation-field" })

        </div>
    }
    @if (@Model.isAStortyTelling)
    {
        <div class="form-group">
            @Html.LabelFor(x => Model.DescriptionStoryTelling, new { @class = "label-required", @for= "PhotoDescription_1" })
            @Html.TextAreaFor(x => Model.DescriptionStoryTelling, new { @class = "form-control photo-description", id = "PhotoDescription_1", rows = 5, maxlength = 250})
            @Html.ValidationMessageFor(x => Model.DescriptionStoryTelling, "")

        </div>
    }
        <div class="form-group">
            @Html.LabelFor(x => Model.FeedBackRequest, new { @class = "label-required" })
            <label class="radiobutton-label">
                @Html.RadioButtonFor(x => Model.FeedBackRequest, true, new { id = "FeedBackRequest_true_1", @class = " photo-feedback_true submit-radiobutton" })
                <span class="radiomark"></span>
                @Html.Label("FeedBackRequest-true", "Yes", new { @class = "label-radiobutton label-true", @for = "FeedBackRequest_true_1" })
            </label>
            <label class="radiobutton-label">
                @Html.RadioButtonFor(x => Model.FeedBackRequest, false, new { id = "FeedBackRequest_false_1", @class = "photo-feedback_false submit-radiobutton" })
                <span class="radiomark"></span>
                @Html.Label("FeedBackRequest-false", "No", new { @class = "label-radiobutton label-false", @for = "FeedBackRequest_false_1" })
            </label>
                @Html.ValidationMessageFor(x => Model.FeedBackRequest, "")

        </div>
    @Html.HiddenFor(x => Model.isAStortyTelling)
</div>